## A test config to run the benchmark

deconv_methods: ["NNLS", "MixUpVI"]
evaluation_datasets: ["CTI", "BULK_FACS"]
granularities: ["2nd_level_granularity", "FACS_1st_level_granularity"]
evaluation_pseudobulk_samplings: ["DIRICHLET"]
signature_matrices: ["CTI_2nd_level_granularity", "FACS_1st_level_granularity"]
train_dataset: "CTI"
n_variable_genes: 3000
save: False
experiment_name: "test_benchmark"
